language: node_js
node_js: stable
notifications:
  email: false
  slack:
    secure: X5FueQUweyPCgqyUIH5f4GZMxiws04+fAHII11YhadqknPVoNU6jXF5PwZKDQZUM8m7qaqN3qigPkpIvLwCE+XsLKd+M8SLbs8NoWGLxgT91Ofijm827l8d/hFzOgcg+KUAZb23G63lLckyCq/4tyN0T+wPlESgKz3Ljw7itQuuu4tdOOX3l3fCs9GD+sOONT/WEcgN52gKiBSLXnQrXilOZNndE95WTS++EixhIGnFiomjnih56PBro1er9PhzYYu4Ci5JXjygn4NkUnJTI5pR1SRA9mZn6nNxzkeSZos2F89HbQbkQ9YHrx4VEpKnJA/2z2oiFVLiDEq9V7lKv/LA/eFFDWkBVEx+s0nCctuKCUKuAFEZMPqnIB6YkqOR3VzwFIuQ9yV49pkVHfOVH6NBRlBzztAFYTs/Ek3tILHS0ekEUbYHYhWyxhYejbYRjFaqIfCl2AqfGnds4SOQE4E5nQz+HBb3GVjAZS4y3FyA90BwcOcHXxv0Ugyu5ru0CjUu585gMExFQ80wkXSu/tiqejAwH4F4VUdiDhz4jJudau/0n6QFHNSqYaWrvb8B9xgr8tvtoF9k6C1aGxuJEiYJrHY7IZwpWHnNjBDqOIhfCPXC0HZD+pn/cajFdtWhPBo0pt3PuXUbh6txu0vexrpyz3TemNoEqbx49e+6thZ8=
